FROM golang:1.23.0 as builder

WORKDIR /app
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o api-server ./cmd/api/main.go

FROM debian:bullseye-slim
WORKDIR /app
COPY --from=builder /app/api-server .
COPY .env .env

ENV PORT=8081

CMD ["./api-server"]